# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/currency_rates.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/currency_rates.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eprotobufs/currency_rates.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n\x0bRateRequest\x12\x0c\n\x04sell\x18\x01 \x01(\t\x12\x0b\n\x03\x62uy\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x15\n\x04Rate\x12\r\n\x05value\x18\x01 \x01(\x01\x32)\n\x05Rates\x12 \n\x07GetRate\x12\x0c.RateRequest\x1a\x05.Rate\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_RATEREQUEST = _descriptor.Descriptor(
  name='RateRequest',
  full_name='RateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sell', full_name='RateRequest.sell', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buy', full_name='RateRequest.buy', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='RateRequest.timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=154,
)


_RATE = _descriptor.Descriptor(
  name='Rate',
  full_name='Rate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Rate.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=177,
)

_RATEREQUEST.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['RateRequest'] = _RATEREQUEST
DESCRIPTOR.message_types_by_name['Rate'] = _RATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RateRequest = _reflection.GeneratedProtocolMessageType('RateRequest', (_message.Message,), {
  'DESCRIPTOR' : _RATEREQUEST,
  '__module__' : 'protobufs.currency_rates_pb2'
  # @@protoc_insertion_point(class_scope:RateRequest)
  })
_sym_db.RegisterMessage(RateRequest)

Rate = _reflection.GeneratedProtocolMessageType('Rate', (_message.Message,), {
  'DESCRIPTOR' : _RATE,
  '__module__' : 'protobufs.currency_rates_pb2'
  # @@protoc_insertion_point(class_scope:Rate)
  })
_sym_db.RegisterMessage(Rate)



_RATES = _descriptor.ServiceDescriptor(
  name='Rates',
  full_name='Rates',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=179,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRate',
    full_name='Rates.GetRate',
    index=0,
    containing_service=None,
    input_type=_RATEREQUEST,
    output_type=_RATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RATES)

DESCRIPTOR.services_by_name['Rates'] = _RATES

# @@protoc_insertion_point(module_scope)
