# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobufs import currency_rates_pb2 as protobufs_dot_currency__rates__pb2


class RatesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRate = channel.unary_unary(
                '/Rates/GetRate',
                request_serializer=protobufs_dot_currency__rates__pb2.RateRequest.SerializeToString,
                response_deserializer=protobufs_dot_currency__rates__pb2.Rate.FromString,
                )


class RatesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RatesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRate,
                    request_deserializer=protobufs_dot_currency__rates__pb2.RateRequest.FromString,
                    response_serializer=protobufs_dot_currency__rates__pb2.Rate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Rates', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Rates(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Rates/GetRate',
            protobufs_dot_currency__rates__pb2.RateRequest.SerializeToString,
            protobufs_dot_currency__rates__pb2.Rate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
