# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: currency_rates.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'currency_rates.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63urrency_rates.proto\x12\tprotobufs\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n\x0bRateRequest\x12\x0c\n\x04sell\x18\x01 \x01(\t\x12\x0b\n\x03\x62uy\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x15\n\x04Rate\x12\r\n\x05value\x18\x01 \x01(\x01\x32=\n\x05Rates\x12\x34\n\x07GetRate\x12\x16.protobufs.RateRequest\x1a\x0f.protobufs.Rate\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'currency_rates_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATEREQUEST']._serialized_start=68
  _globals['_RATEREQUEST']._serialized_end=155
  _globals['_RATE']._serialized_start=157
  _globals['_RATE']._serialized_end=178
  _globals['_RATES']._serialized_start=180
  _globals['_RATES']._serialized_end=241
# @@protoc_insertion_point(module_scope)
